### ISSUE TITLE
SMBX Pre-1.3 compatibility

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#185]
To make proper work of older levels and episodes developed for SMBX versions older than 1.3, we need to provide the compatibility for given file versions and set up different behavior for features. Some of them were done already.

The full list of pre-1.3 compatibility features:
- [x] Different behavior for Bowser the Third
- [x] Billy gun (NPC-22) should shoot 2x time slower when version less than 28 and should keep shooting while projectile if version less than 51.
- [x] Thwomp (NPC-37) should always fall with no matter to the Y coordinate of a player. Version less than 9.
- [x] Need to fix bug #169 with the platform blocks (NPC-60), right now here is a workaround made. Otherwise, the platform will be stuck at the "Clown car" level of "The Invasion" episode. Version less than 9.
- [ ] Disable the spin-jump ability for players at builds before 20
- [ ] Make Luigi physics act the same as Mario at builds before 51
- [ ] Before build 51, players shouldn't be able to grab a shell from above
- [ ] Toad shouldn't be able to spin-jump when a version is older than 64.
- [ ] Boo (NPC-38) should fly a bit faster
- [ ] Mario and Luigi should automatically drop the reserve item when the version is older than 51
- [ ] Before X version (probably version 30), have the higher section top limit (that's required to get the secret exit at "P-Switch Panic" level because the flying over the wall is required) [NEED AN INFO]
- [x] Before build 58, Mario and Luigi only existed (#223)
- [ ] Before build 51, you can't choose between Mario and Luigi as a first player (#223)
- [ ] Before build 30, Thwomps, Boos, and Eeries are fully immortal, nothing can kill them

## Notes
- All pre-1.3 compatibility features should work when the compatibility level is set to MODERN (Mode 1). If the compatibility level is SMBX2 (Mode 2) or SMBX1.3 (Mode 3), all pre-1.3 compatibility features should be disabled.

**Comment by ds-sloth** [comment]
This looks really exciting to me and should be a great way to preserve SMBX history.

How can we determine the exact speed of NPC-38A in older versions? Do we need to reverse engineer? (Too bad we only have the V64 source and not each version's source.)

**Comment by LoveBodhi** [comment]
Toad can spin jump since 1.3

**Comment by Wohlstand** [comment]
>  NPC-38A -> NPC-38

Damn, by reflexes I type A after I type "38" :rofl:

**Comment by Wohlstand** [comment]
> How can we determine the exact speed of NPC-38A in older versions? Do we need to reverse engineer? (Too bad we only have the V64 source and not each version's source.)

Looks like yes, we should check out for some here... :thinking:

**Comment by Wohlstand** [comment]
Anyway, there are several hints still be in the VB6 code that helped me to repair Bowser the Third's original logic and Billy Gun logic.

**Comment by Wohlstand** [comment]
> Is there a way to disable this? There should be a way to reproduce the 1.3 Behavior for Pre-1.3 Episodes, both, for personal preference, and for Speedruns, as 1.3 is the preferred Version for those (and the ability to play as Toad gives an advantage).

Once you run any compatibility mode that is not "modern", this going to be disabled

**Comment by ds-sloth** [comment]
I think I mentioned in a separate thread that it might be better to introduce a fourth compat mode for these behaviors, so modern -> smbx2 -> smbx1.3 -> ancient modes. Then these things would only happen in the "ancient mode".

**Comment by 0lhi** [comment]
> There is already a thing that once you run any compatibility mode that is not "modern", this going to be disabled

@Wohlstand Can't confirm. Playing _Great Castle Adventure_ with any Compatibility Mode will disable Characters.

@ds-sloth I think the ancient mode should be also available via a compat.ini or thextech.ini trigger.

**Comment by Wohlstand** [comment]
> Compatibility Mode will disable Characters.

Easy to fix, I just forgot to add an exception for that. So, if that doesn't works, the it's a bug: when using non-modern mode, all pre1.3 checks must be disabled include ability to play with unavailable characters.

Anyway, general idea of compatibility is not just "everything", and the "ancient mode" sounds overhead, because there is a doze of features that has difference among many versions (Billy gun has 3 different variants of behavior, not 2), and they get toggled differently from the same version number. But, for NPC cases there are added special values (available through TheXTech SDK) that can be changed to alter behavior of NPC and reproduce an older behavior of it.

Mainly:
- Modern mode, allows all bugfixes and supports pre1.3 compatibility tweaks that gets enabled for older level file formats
- X2 mode, disables all bugfixes except these are same at X2 project. Pre1.3 tweaks always disabled except level files that tells NPC work differently.
- Strict mode, disables all bugfixes to reproduce full 1.3 behavior with all bugs and also disables pre1.3 tweaks.

**Comment by Wohlstand** [comment]
@0lhi, just now I made the check, and using `--compat-level smbx13`, the same episode shows a different list of players: with the modern mode, it shows up the Mario and Luigi only, and with other compatibility modes it shows all 5 characters.

**Comment by 0lhi** [comment]
>  and they get toggled differently from the same version number.

I mean, yeah, my idea (and I think that's what ds-sloth meant, too) is that with ancient mode, it would read the version number, and then choose the Billy Gun Mode that's appropriate for it. Ancient Mode would basically be Mode 3 + Pre1.3 reading enabled.

> Modern mode, allows all bugfixes and supports pre1.3 compatibility tweaks that gets enabled for older level file formats

This should be optional. For Modern Mode, the Player should be able to decide whether to enable the Pre1.3 stuff or not:

```ini
[compatibility]
enable-pre-smbx64-adjusting = true
```

Mode 1 would allow the Player to choose.
Mode 2 and 3 would forcefully disable it.
Mode 4 (Ancient Mode) would forcefully enable it.

**Comment by 0lhi** [comment]
Adding to my last comment, I think it would make sense to differentiate between the Pre-1.3 Adjustments that may be needed for beating an episode (such as Bowser III behavior) versus those that put a limitation on the Player (like blocking Characters/Abilities).

```enable-pre-smbx64-adjusting``` could have three options:

- ```full```: enable everything. (Mode 4)
- ```minimal```: enable the necessary stuff. (Default)
- ```false```: disable everything. (Mode 2+3)

**Comment by 0lhi** [comment]
Or, even better, make two settings:

```enable-features-for-pre-smbx64``` would be ```= true``` by default and handle these things:

* *Different behavior for Bowser the Third*
* *Billy gun (NPC-22) should shoot 2x time slower when version less than 28 and should keep shooting while projectile if version less than 51.*
* *Thwomp (NPC-37) should always fall with no matter to the Y coordinate of a player. Version less than 9.*
* *Need to fix bug Switch platform gets stuck on rail buffer and won't move after being enable #'169 with the platform blocks (NPC-60), right now here is a workaround made. Otherwise, the platform will be stuck at the "Clown car" level of "The Invasion" episode. Version less than 9.*
* *Boo (NPC-38) should fly a bit faster*

```enable-limitations-for-pre-smbx64``` would be ```= false``` by default and handle these things:

* *Disable the spin-jump ability for players at builds before 20*

* *Make Luigi physics act the same as Mario at builds before 51*

* *Before build 51, players shouldn't be able to grab a shell from above*

* *Toad shouldn't be able to spin-jump when a version is older than 64.*

* *Mario and Luigi should automatically drop the reserve item when the version is older than 51*

* *Before X version (probably version 30), have the higher section top limit (that's required to get the secret exit at "P-Switch Panic" level because the flying over the wall is required) [NEED AN INFO]*

* *Before build 58, Mario and Luigi only existed*

* *Before build 51, you can't choose between Mario and Luigi as a first player*

* *Before build 30, Thwomps, Boos, and Eeries are fully immortal, nothing can kill them*

Mode 2/3 disables, Mode 4 enables both.

**Comment by P-Star7** [comment]
Before Build 20, all instances of block-90 (SMW Flip Block) act exactly the same as a normal brick, and continue to make their usual effect of effect-1 when broken. This affects Adventures of Demo.

**Comment by Wohlstand** [comment]
at AOD I converted all levels into LVLX/WLDX set, so, shouldn't affect

**Comment by P-Star7** [comment]
Unknown, all likely before Build 28:
-Piranha Plants move up and down/left and right instead of disappearing. They do not "hide themselves". This also means that Yoshi can eat them and block-penetrating NPCs and harms (Toothy, Yoshi fire, vegetables, Hammer Bro's hammer, thrown Cheep-Cheep, SMB3 Bob-omb explosion, SMB2 Bomb/Bob-omb explosion) will kill them even when they are inside the pipe.
-Yoshi can eat sprouts that contain any NPC that is tagged as Yoshi-edible, as well as all sprouts that contain coins. This makes him either eat the enemy, power-up, or coin, or if it is something that he can hold in his mouth, he does so.
-Bowser III's lower health (must check)

Before Build 28 or 32 (whichever one introduced water and new Cheep Cheeps, I must check)
-The SMB1 Red Cheep Cheep can be picked up and thrown like a SMB2 enemy. Notice the graphics. Similar to a vegetable (and as a reference to Trouter from SMB2), it never "lands" on solid ground and just goes through it, it does not return to its former flying behaviour when thrown or dropped.

**Comment by P-Star7** [comment]
Before Build 64:
-Wart is immune to ALL damage except for when he is shooting. This includes while he is walking or hurt.
-Mother Brain's Glass is vulnerable to fireballs. 3 fireballs = 1 crack. 15 HP in total.

**Comment by P-Star7** [comment]
Relevant code for Peach and Toad's powerup-state forcing in builds below 64. Uncomment it to see it in action.
https://github.com/Wohlstand/smbx-experiments/blob/3b5d942a0566b5c4507750be2af79d3621682f4a/modPlayer.bas#L1741

**Comment by 0lhi** [comment]
I'd like to reconsider this one.

There are a total of 14 Pre-64 Episodes on @Wohlstand's Server. This hardly justifies the effort of maintaining an automatic compatibility system, which adds additional baggage to the goal of designing an intuitive yet powerful UI.

Many of the things listed here can already be achieved with minor changes to the episode:

> Disable the spin-jump ability for players at builds before 20
> Toad shouldn't be able to spin-jump when a version is older than 64.

Spin-Jumps can be disabled with Autocode.

> Boo (NPC-38) should fly a bit faster

Can be done with npc-38.txt.

> Before build 58, Mario and Luigi only existed

Very easy to change with a .wld edit.

Other changes like setting the new NPC Special Flags could be handled by the Moondust Maintainer.

In my opinion, there is no reason to treat Pre-64 any differently than 38A and X2: Adapt cool stuff where convenient, but don't prioritize full compatibility in order to avoid over-complication.

Out of the 14 Episodes in Wohl's Server, 5 have a working 1.3 Counterpart. The remaining 9 and other episodes that weren't ported to 1.3 during it's 10 years of dominance are most probably not worth it.

**Comment by Wohlstand** [comment]
> Boo (NPC-38) should fly a bit faster

I probably made something like, I had added the multiplication factor already (I need to verify, did I that or not) :eyes:

**Comment by ds-sloth** [comment]
I think we should focus on making sure pre-1.3 content is playable. Unlike 38A and X2, there is no team currently maintaining pre-1.3 engines and working to preserve their content.

But I don't think we need to, or should try to, exactly match pre-X64 behavior. We're never going to match pre-1.3 behavior exactly, and details like the NPC-38 speed aren't important to playability.

Also, I would propose reverting the change that allowed the user to place both pre-X64 and X64 variants of objects in the same level. (Spin-blocks, the expand section feature, spinning gears algorithm, etc.)

This feature over-complicates the game engine, costs quite a bit of RAM (160kb for blocks, 40kb for NPCs), and adds confusion about how the objects will behave. Instead, we should ensure that `lvlx` files can specify that they target a pre-1.3 version, and if pre-SMBX64 targeting is enabled, global flags should be set that determine the correct behaviors for each object type.

If we take that approach, then in the future, if a creator wants to mix pre-X64 and X64 variants, they could use scripting to create new NPCs that emulate the pre-1.3 behavior, instead of per-object variants.

**Comment by 0lhi** [comment]
> I think we should focus on making sure pre-1.3 content is playable. Unlike 38A and X2, there is no team currently maintaining pre-1.3 engines and working to preserve their content.

The reason why there is no team is because for 9 years people just didn't care. Again, it's 14minus5 episodes. Out of the 9 that have no 1.3 Counterpart, only one (The Invasion) is known to have gamebreaking Issues, which are trivial to fix (as demonstrated by Adventures of Demo).

> I think we should focus on making sure pre-1.3 content is playable. [...]
> But I don't think we need to, or should try to, exactly match pre-X64 behavior.

If making the content playable is sufficing, that can already be done. In fact, it can even be done without altering how the Episodes would behave on Pre-1.3.

The secret: Autocode.

Put the gamebreaking objects inside a layer. 

Add gamefixing objects inside a hidden layer.

Have Autocode hide the gamebreaking layer and show the gamefixing layer.

BONUS: Episode is now playable on the two main branches of SMBX: X2 and TheXTech, making them Speedrun-viable.

If a Team is truly concerned with preserving Pre-1.3 Content, that's how it should be done.

Adjusting the engine to 14 ancient episodes of questionable quality is a bad idea.

**Comment by ds-sloth** [comment]
The core development team has decided that attempting to automatically target pre-SMBX64 versions is no longer a priority, and I believe I have removed all existing pre-SMBX64 targeting.

For those of you following this thread, we made this decision due to a few fundamental issues with version targeting:
- The detected format changes if a level is edited in any way in SMBX 1.3, TheXTech, or Moondust
- We can never get perfect pre-1.3 compatibility (don't have pre-1.3 source)
- There is a very limited amount of pre-1.3 content, and this content is almost fully compatible with 1.3


Archived Pre-1.3 content should be updated for this situation by changing the format to `lvlx` and setting the following flags:
- For content previously targeting SMBX19 and older, set the "force smashable" flag for any turn blocks.
- The held cannon's behavior changed at releases 51 and 28. Set the 1.2.0 behavior or Pre-1.2 behavior for it as needed.
- The falling stone ("Thwomp") enemy's behavior changed at release 9. In very ancient content, it falls even when the player is not below it. Set the "Fall Always" option if needed.
- The main villain ("Bowser III")'s behavior changed at release 30. This is an important change because the old behavior expanded the section. Set this behavior as needed.
- The behavior of the lineguide platforms and saw changed in release 30. Set the Pre-1.2 behavior as needed.


@Wohlstand, how much content needs to be updated? Shall we wait until we have converted the content before closing this issue?

**Comment by 0lhi** [comment]
> Shall we wait until we have converted the content before closing this issue?

Since that is a concern of the Content and not of the Engine (anymore), I'm gonna close it now and recommend to reopen on the Moondust repo, where Pre-1.3 adjustments should be handled by the Maintainer at conversion-time.
