### ISSUE TITLE
[List] Backport all `devel` features into `master`

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#232]
To continue the main development process, we SHOULD port all major features made at the `devel` branch into the mainstream. Initially, that branch was intended for the debugging stuff, however, it has grown into the big unpolished thing that I still need to deeply review. Also, some features such as QuadTree optimization would require some rework (for example, making the sort of a tilemap optimization, but making it work for two directions, not linearly, also, make own arrays per layer to avoid the DrPepper problem).

**List of features:**
- [x] **Multi-resolution** - allows changing the in-game resolution into any different than 800x600, but made that smartly. (#328)
- [x] **Layers now track the objects they contain in sets**
- [x] **Solution for [DrPepper Problem](https://wohlsoft.ru/pgewiki/DrPepper_Problem) and blocks search optimization** (#33)  (depends layers, can be improved)
- [x] **File system case sensitivity workaround optimizations**
- [x] **Strings replaced with numbers** for layer and event names to reduce the general memory use and increase the general performance while processing layers and events (depends on layers)
- [x] 3DS platform support (depends multires, abstract controls) (#366)
- [x] **PS Vita platform support** ~~(depends multires)~~ Done without it
- [x] **Records replaying system**
- [x] **New in-game editor** (depends abstract controls)
- [x] Config option to enable fast move at the world map (https://github.com/Wohlstand/TheXTech/commit/8c123ed19ae7c0a5c906c3a94cc3d70be75365b3)

**Fix bugs:**
- [x] Touch-screen actions for "hold run" mode should always work on Press with a cost of one frame, never for release, as this behavior confuses and makes gameplay being messed up (#363)
- [x] Repair the regression of the magic hand functionality (accessible when running a level test using Moondust Editor)

// p.s. Please add items I forgot

**How to do the work**
- Choose the task for the work
- Make the branch from the `master`
- Manually apply all changes made at the `devel` branch to reach the goal of the task, or, re-implement the thing differently if there is a better solution was found
- Make a pull request that we should review together

**Comment by LoveBodhi** [comment]
There are some unlisted features as well...

**Comment by ds-sloth** [comment]
On my end: from my and Axiom's profiling I think that we can do much better than my first block search code. In particular i don't think the quadtree is the right structure to use here. So we may want to think about revising this code as we backport it.

Second, the abstract controls code is feature complete but I want to test it some more before we make it the default. And two of the features depend on abstract controls: (1) proper 3DS port and (2) new in-game editor (for text entry and configuration). So maybe those two features can be a part of 1.3.7? (However, beta 3DS port without working controller configuration can be finished with 1.3.6.)

**Comment by ds-sloth** [comment]
Additionally, there is the layers performance optimization (each layer has a standard set containing its objects, and each object represents its layer by an index, not a string) and the strings RAM optimization (all strings are replaced by indices into a global string map).

**Comment by LoveBodhi** [comment]
Script System, Parallax Backgrounds, are unlisted (But planned).

**Comment by ds-sloth** [comment]
These are the features that are already implemented but not in the main branch. We are also excited to do these features after.

**Comment by Wohlstand** [comment]
> Script System, Parallax Backgrounds, are unlisted (But planned).

As @ds-sloth said, this list contains features that were already implemented. Features are not implemented, going at separated tasks.

**Comment by Wohlstand** [comment]
I set the "Records replaying system" being completed as the thing was been added, but, it has some cases to be completed, mainly, tune out the random generator and making the isolated random instance for the non-gameplay cases to don't confuse the seed state while recording on "SMBX Experiments" to replay on TheXTech.

**Comment by Wohlstand** [comment]
Just now, @ChristianSilvermoon at issue #70 reminded us about another nifty feature that we need to backport, so, I added it into the list

**Comment by Wohlstand** [comment]
Editor branch has been merged, I marked "New Editor" as done. The editor itself is not so finished and requires more work to be a more stable thing. So, it is kept as an experimental feature that can be enabled from `settings/thextech.ini` separately.

**Comment by ds-sloth** [comment]
Minor point, but I just backported the episode title display option that @0lhi requested. It's a small feature so I sent it straight to the main branch.

**Comment by Wohlstand** [comment]
Little note that recently I made the little optimization of the DirListCI thing: https://github.com/Wohlstand/TheXTech/blob/master/lib/Utils/dir_list_ci.cpp

Now, lists of sub-directories get cached on the first request, and that should avoid multiple reconstructions of the same subdirectory's instance.

**Comment by Wohlstand** [comment]
Forgot to check, that Magic Hand integration with Moondust Editor works fine.

**Comment by Wohlstand** [comment]
The touchscreen controller task has been completed.

**Comment by LoveBodhi** [comment]
Multires isn't a milestone of 1.3.6!

**Comment by ds-sloth** [comment]
Multires is now merged into the main branch! @Wohlstand, shall we finally close this issue, or wait for all Multi-res stabilization issues to be fully implemented, tested, and closed?

**Comment by Wohlstand** [comment]
Ye, this can be closed now. As main goal of this list had been completely solved. The stabilisation is a general thing that goes outside of this scope.
