### ISSUE TITLE
Prepare for 1.3.6.1 release, TODO list

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/TheXTech#615]
# Actualise WIKI:
- [x] Actualize ["compat.ini" page](https://github.com/Wohlstand/TheXTech/wiki/compat.ini---Tune-the-compatibility)
- [x] Actualize [memory emulator mapping page](https://github.com/Wohlstand/TheXTech/wiki/LunaScript-Memory-Map)
- [x] Actualize "gameinfo.ini" page
- [x] Actualize the ["settings/thextech.ini" page](https://github.com/Wohlstand/TheXTech/wiki/thextech.ini---Tune-game-settings)
- [x] Actualize [CMake arguments page](https://github.com/Wohlstand/TheXTech/wiki/CMake-parameters-explained)
- [x] Add 3DS build manual
- [x] Add Wii build manual
- [x] Write "[Customise a playable character](https://github.com/Wohlstand/TheXTech/wiki/Customise-a-playable-character)" article (reference to the Moondust Calibrator tool and explanation what features of player INI files were supported)

# Stabilisation
- [x] Verify the stability of 3DS side.
- [x] Verify the stability of controls in 2P replays.
- [x] Verify the stability of controls in SingleCoop
- [x] Verify that pause menu does not have lockout during SingleCoop + compat mode

# Things
- [x] Add a command-line argument to return JSON string to print capabilities of the build (to provide an accurate set of features that this build supports, needed for Moondust Editor to enable/disable necessary options).
- [ ] Close #620 after Wohlstand confirms
- [x] Add all audio formats to new_editor.cpp:1788 (see d4e4259937114e5ae6be2ab6eba5d9d50969b2b4)

**Comment by LoveBodhi** [comment]
I should verify Nostalgic Paradise by the same time...

**Comment by Wohlstand** [comment]
Added command-line `--capabilities` argument that returns a JSON string (feature gets enabled on builds with only these builds that has IPC support being enabled):
https://github.com/Wohlstand/TheXTech/commit/eebca695c6fd6114f09a811379d9b1f573ffb12a

**Comment by ds-sloth** [comment]
I have just stabilized the controls in cloned player (superbdemo128) mode, single coop (superbdemo2) mode, and 2P gameplay records.

This fixes at least one noticeable TheXTech 1.3.6 bug where the player could get stuck in the pause menu during single coop mode.

**Comment by Wohlstand** [comment]
I'll close this as 1.3.6.1 had been released.
